### ISSUE TITLE
why is this type of error showing?? plz reply after coding  perfect

### ISSUE THREAD

**Issue by Satyamkrsks** [ProgrammingHero1/romantic-alexa#105]
Traceback (most recent call last):
  File "C:/Users/SATYAM SHIVANI/PycharmProjects/jarvis 2/main.py", line 3, in <module>
    import pywhatkit
  File "C:\Users\SATYAM SHIVANI\PycharmProjects\jarvis 2\venv\lib\site-packages\pywhatkit\__init__.py", line 29, in <module>
    from pywhatkit.remotekit import start_server
  File "C:\Users\SATYAM SHIVANI\PycharmProjects\jarvis 2\venv\lib\site-packages\pywhatkit\remotekit.py", line 6, in <module>
    from flask import Flask, request
ModuleNotFoundError: No module named 'flask'

**Comment by JJRoyale** [comment]
yes i dont know

**Comment by Satyamkrsks** [comment]
okk now it has been solved

**Comment by chez-main** [comment]
write pip install flask

**Comment by JJRoyale** [comment]
Ok ok thank you
