### ISSUE TITLE
I'm having a issue

### ISSUE THREAD

**Issue by franciscoabsilva** [ProgrammingHero1/romantic-alexa#11]
"C:\Users\Francisco Silva\Desktop\webscrapping_clubs\Alexa\Scripts\python.exe" "C:/Users/Francisco Silva/Desktop/Coding/Python/Alexa/Alexa.py"
listening...
Traceback (most recent call last):
  File "C:/Users/Francisco Silva/Desktop/Coding/Python/Alexa/Alexa.py", line 60, in <module>
    run_alexa()
  File "C:/Users/Francisco Silva/Desktop/Coding/Python/Alexa/Alexa.py", line 35, in run_alexa
    command = take_command()
  File "C:/Users/Francisco Silva/Desktop/Coding/Python/Alexa/Alexa.py", line 31, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

Process finished with exit code 1

**Comment by ashraf-minhaj** [comment]
See this https://github.com/ProgrammingHero1/romantic-alexa/issues/5
