### ISSUE TITLE
Why is this error showing?

### ISSUE THREAD

**Issue by JJRoyale** [ProgrammingHero1/romantic-alexa#110]
Traceback (most recent call last):
  File "C:/Users/username/PycharmProjects/alexa/main.py", line 60, in <module>
    run_alexa()
  File "C:/Users/username/PycharmProjects/alexa/main.py", line 35, in run_alexa
    command = take_command()
  File "C:/Users/username/PycharmProjects/alexa/main.py", line 31, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

**Comment by JJRoyale** [comment]
use pip install flask

Il giorno mar 29 mar 2022 alle ore 16:57 erieeej ***@***.***>
ha scritto:

**Comment by stratosvomvos** [comment]
Hey, JJRoyale. 
I liked your project |pybrowser| and i made it a standalone executable [that will work in all devices with no installing] (it may be slow first run) 
|DOWNLOAD|
https://mega.nz/file/sZdg0RhL#fR63DKaN-8AS7oAoRucnC7nnFvSWVUHoba4o4gON1VI

**Comment by ashraf-minhaj** [comment]
Make sure your internet connection is good enough.

**Comment by DanielAlexandruCocolos** [comment]
i have the same issues, please tell us a fix

**Comment by phareze** [comment]
https://www.youtube.com/watch?v=Zh6gb3nFUPs

**Comment by jinimbi** [comment]
Was anyone successful in solving this? I am using a mac m1 and nothing has worked so far.

**Comment by AVAT1010** [comment]
The problem is with your connection, use a good VPN, it should work

**Comment by REALAVAT** [comment]
> Traceback (most recent call last): File "C:/Users/username/PycharmProjects/alexa/main.py", line 60, in run_alexa() File "C:/Users/username/PycharmProjects/alexa/main.py", line 35, in run_alexa command = take_command() File "C:/Users/username/PycharmProjects/alexa/main.py", line 31, in take_command return command UnboundLocalError: local variable 'command' referenced before assignment

***The problem is with your connection, use a good VPN, it should work***

**Comment by Projato** [comment]
Uhh just reinstall pyaudio, via pip or pipwin.
