### ISSUE TITLE
issues: Traceback (most recent call last)  import pywhatkit / from .remotekit import start_server / cli = sys.modules["flask.cli"] KeyError: 'flask.cli'

### ISSUE THREAD

**Issue by Akrantor** [ProgrammingHero1/romantic-alexa#112]
hey there can anyone help me out with this one? 

**Traceback (most recent call last):
  File "C:\Users\rausc\PycharmProjects\myra\main.py", line 3, in <module>
    import pywhatkit
  File "C:\Users\rausc\PycharmProjects\myra\venv\lib\site-packages\pywhatkit\__init__.py", line 29, in <module>
    from .remotekit import start_server
  File "C:\Users\rausc\PycharmProjects\myra\venv\lib\site-packages\pywhatkit\remotekit.py", line 11, in <module>
    cli = sys.modules["flask.cli"]
KeyError: 'flask.cli'**

Process finished with exit code 1

**Comment by Akrantor** [comment]
okay i figured it out: 
for all it isnt said in the tutorial but it is really logic. 

if you got this error: just pip install flask.... 

bye have a great day :D
