### ISSUE TITLE
pywhatkit error

### ISSUE THREAD

**Issue by Nishanth-47** [ProgrammingHero1/romantic-alexa#114]
Traceback (most recent call last):
  File "C:\Users\J.Nishanth\PycharmProjects\voiceassistant\main.py", line 3, in <module>
    import pywhatkit
  File "C:\Users\J.Nishanth\PycharmProjects\voiceassistant\venv\lib\site-packages\pywhatkit\__init__.py", line 29, in <module>
    from pywhatkit.remotekit import start_server
  File "C:\Users\J.Nishanth\PycharmProjects\voiceassistant\venv\lib\site-packages\pywhatkit\remotekit.py", line 6, in <module>
    from flask import Flask, request
ModuleNotFoundError: No module named 'flask'

**Comment by Addycyber** [comment]
same error

**Comment by DEV1234simple** [comment]
> Traceback (most recent call last): File "C:\Users\J.Nishanth\PycharmProjects\voiceassistant\main.py", line 3, in import pywhatkit File "C:\Users\J.Nishanth\PycharmProjects\voiceassistant\venv\lib\site-packages\pywhatkit__init__.py", line 29, in from pywhatkit.remotekit import start_server File "C:\Users\J.Nishanth\PycharmProjects\voiceassistant\venv\lib\site-packages\pywhatkit\remotekit.py", line 6, in from flask import Flask, request ModuleNotFoundError: No module named 'flask'

same for me

**Comment by allenlopes** [comment]
> Traceback (most recent call last): File "C:\Users\J.Nishanth\PycharmProjects\voiceassistant\main.py", line 3, in import pywhatkit File "C:\Users\J.Nishanth\PycharmProjects\voiceassistant\venv\lib\site-packages\pywhatkit__init__.py", line 29, in from pywhatkit.remotekit import start_server File "C:\Users\J.Nishanth\PycharmProjects\voiceassistant\venv\lib\site-packages\pywhatkit\remotekit.py", line 6, in from flask import Flask, request ModuleNotFoundError: No module named 'flask'

Just install Flask on Pycharm with this command ->  'pip install flask' and your 3rd error will be disappeared.

**Comment by allenlopes** [comment]
> > Traceback (most recent call last): File "C:\Users\J.Nishanth\PycharmProjects\voiceassistant\main.py", line 3, in import pywhatkit File "C:\Users\J.Nishanth\PycharmProjects\voiceassistant\venv\lib\site-packages\pywhatkit__init__.py", line 29, in from pywhatkit.remotekit import start_server File "C:\Users\J.Nishanth\PycharmProjects\voiceassistant\venv\lib\site-packages\pywhatkit\remotekit.py", line 6, in from flask import Flask, request ModuleNotFoundError: No module named 'flask'
> 
> same for me

Just install Flask on Pycharm with this command -> 'pip install flask' and your 3rd error will be disappeared.

**Comment by allenlopes** [comment]
> same error

Just install Flask on Pycharm with this command -> 'pip install flask' and your 3rd error will be disappeared.
