### ISSUE TITLE
UnboundLocalError 

### ISSUE THREAD

**Issue by oochrjames** [ProgrammingHero1/romantic-alexa#115]
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/DELL/Documents/vic/main.py", line 60, in <module>
    run_alexa()
  File "C:/Users/DELL/Documents/vic/main.py", line 35, in run_alexa
    command = take_command()
  File "C:/Users/DELL/Documents/vic/main.py", line 31, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

**Comment by Projato** [comment]
Hi!

What software are you using?
I'm presuming it's pycharm and so you should be able to see a "Python Packages" option on the bottom left beside the terminal.
Go to packages and then search up pyaudio, if it is in already installed, uninstall it and re-install it from python packages.
Your program should run fine after that!
