### ISSUE TITLE
the error is showing like this for me

### ISSUE THREAD

**Issue by vigggs** [ProgrammingHero1/romantic-alexa#121]
Traceback (most recent call last):
  File "C:\Users\venui\PycharmProjects\Virtual Assistant\main.py", line 60, in <module>
    run_alexa()
  File "C:\Users\venui\PycharmProjects\Virtual Assistant\main.py", line 35, in run_alexa
    command = take_command()
  File "C:\Users\venui\PycharmProjects\Virtual Assistant\main.py", line 31, in take_command
    return  command
UnboundLocalError: local variable 'command' referenced before assignment

**Comment by Projato** [comment]
Hi! 

What software are you using? 
I'm presuming it's pycharm and so you should be able to see a "Python Packages" option on the bottom left beside the terminal.  
Go to packages and then search up pyaudio, if it is in already installed, uninstall it and re-install it from python packages. 
Your program should run fine after that!
