### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by ramiz03** [ProgrammingHero1/romantic-alexa#123]
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hp\PycharmProjects\jarvis2.0\main.py", line 9, in <module>
    engine = pyttsx3.init()
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pyttsx3\driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pyttsx3\drivers\sapi5.py", line 10, in <module>
    import pythoncom
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\win32\lib\pywintypes.py", line 9, in <module>
    engine = pyttsx3.init()
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\pyttsx3\driver.py", line 52, in __init__
    self._driver = self._module.buildDriver(weakref.proxy(self))
AttributeError: partially initialized module 'pyttsx3.drivers.sapi5' has no attribute 'buildDriver' (most likely due to a circular import)

**Comment by Agapt01** [comment]
Traceback (most recent call last):
  File "C:/Users/SL7/PycharmProjects/robot/main.py", line 3, in <module>
    import pywhatkit
  File "C:\Users\SL7\PycharmProjects\robot\venv\lib\site-packages\pywhatkit\__init__.py", line 12, in <module>
    from pywhatkit.handwriting import text_to_handwriting
  File "C:\Users\SL7\PycharmProjects\robot\venv\lib\site-packages\pywhatkit\handwriting.py", line 1, in <module>
    import requests
  File "C:\Users\SL7\PycharmProjects\robot\venv\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\SL7\PycharmProjects\robot\venv\lib\site-packages\urllib3\__init__.py", line 42, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.1.0h  27 Mar 2018'. See: https://github.com/urllib3/urllib3/issues/2168
