### ISSUE TITLE
Facing below errors after running the program in pychram

### ISSUE THREAD

**Issue by keneankit01** [ProgrammingHero1/romantic-alexa#13]
"C:\Users\ANKIT KENE\PycharmProjects\Mybot\venv\Scripts\python.exe" "C:/Users/ANKIT KENE/PycharmProjects/Mybot/main.py"
Traceback (most recent call last):
  File "C:/Users/ANKIT KENE/PycharmProjects/Mybot/main.py", line 60, in <module>
    run_alexa()
  File "C:/Users/ANKIT KENE/PycharmProjects/Mybot/main.py", line 35, in run_alexa
    command = take_command()
  File "C:/Users/ANKIT KENE/PycharmProjects/Mybot/main.py", line 31, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

**Comment by ashraf-minhaj** [comment]
Please see the issue #5
