### ISSUE TITLE
this error occur whenever i run the program

### ISSUE THREAD

**Issue by priyanshuwaghdhare** [ProgrammingHero1/romantic-alexa#137]
listening...
Traceback (most recent call last):
  File "C:\Users\asus\PycharmProjects\xyz\main.py", line 58, in <module>
    command = take_command()
  File "C:\Users\asus\PycharmProjects\xyz\main.py", line 36, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

Process finished with exit code 1

what shuld i do plz.. anyone help me

**Comment by Abreeq** [comment]
Working on this issue.
