### ISSUE TITLE
Error in program

### ISSUE THREAD

**Issue by sarancodes** [ProgrammingHero1/romantic-alexa#22]
Traceback (most recent call last):
  File "C:\Users\Home\PycharmProjects\pythonProject\alexa.py", line 60, in <module>
    run_alexa()
  File "C:\Users\Home\PycharmProjects\pythonProject\alexa.py", line 35, in run_alexa
    command = take_command()
  File "C:\Users\Home\PycharmProjects\pythonProject\alexa.py", line 31, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

Can you please tell what to do ?

**Comment by Stroper111** [comment]
See issue #30  to solve this error and see the real error.

**Comment by ashraf-minhaj** [comment]
See issue #5
