### ISSUE TITLE
I don't know what type error is this

### ISSUE THREAD

**Issue by yuvarajucet** [ProgrammingHero1/romantic-alexa#3]
python3 assistent.py                                                                                                                                  1 ⨯
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "/home/Mr_3rr0r_501/.local/lib/python3.8/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/usr/lib/python3.8/weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "assistent.py", line 9, in <module>
    engine = pyttsx3.init()
  File "/home/Mr_3rr0r_501/.local/lib/python3.8/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "/home/Mr_3rr0r_501/.local/lib/python3.8/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/home/Mr_3rr0r_501/.local/lib/python3.8/site-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/Mr_3rr0r_501/.local/lib/python3.8/site-packages/pyttsx3/drivers/espeak.py", line 9, in <module>
    from . import _espeak, toUtf8, fromUtf8
  File "/home/Mr_3rr0r_501/.local/lib/python3.8/site-packages/pyttsx3/drivers/_espeak.py", line 18, in <module>
    dll = cdll.LoadLibrary('libespeak.so.1')
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libespeak.so.1: cannot open shared object file: No such file or directory

What is the error is this?? 
i installed all the required packages.

**Comment by ashraf-minhaj** [comment]
What is your OS?

**Comment by yuvarajucet** [comment]
kali linux (2020.4)

**Comment by ashraf-minhaj** [comment]
You need to install `portAudo` , `pyAudio` for that.

**Comment by Sdey702** [comment]
For install pyaudio in linux you must be run this command [ I'm  useing linux 20.04]
~$ sudo apt install python3-pyaudio
~$ sudo pip3 install PyAudio
Start your project :)

**Comment by Sdey702** [comment]
python3 assistent.py 1 ⨯
1 x show after enter
~$ python3 assistent.py 
this line ....

**Comment by amsanoussi** [comment]
Try to install espeak

`sudo apt-get update && sudo apt-get install espeak`

It will be solve.

**Comment by ethersecure** [comment]
(venv) c:\Users\suraj\Downloads\romantic-alexa-main\venv>pip install PyAudio
Collecting PyAudio
  Using cached PyAudio-0.2.11.tar.gz (37 kB)
Using legacy 'setup.py install' for PyAudio, since package 'wheel' is not installed.
Installing collected packages: PyAudio
    Running setup.py install for PyAudio ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\suraj\downloads\romantic-alexa-main\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\suraj\\AppData\\Local\\Temp\\pip-install-kfis6pkg\\pyaudio_e840b595f5154cbb8e95536c462412ab\\setup.py'"'"'; __file__='"'"'C:\\Users\\suraj\\AppData\\Local\\Temp\\pip-install-kfis6pkg\\pyaudio_e840b595f5154cbb8e95536c462412ab\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\suraj\AppData\Local\Temp\pip-record-l1f6o9sf\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\suraj\downloads\romantic-alexa-main\venv\include\site\python3.8\PyAudio'
         cwd: C:\Users\suraj\AppData\Local\Temp\pip-install-kfis6pkg\pyaudio_e840b595f5154cbb8e95536c462412ab\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    copying src\pyaudio.py -> build\lib.win32-3.8
    running build_ext
    building '_portaudio' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\suraj\downloads\romantic-alexa-main\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\suraj\\AppData\\Local\\Temp\\pip-install-kfis6pkg\\pyaudio_e840b595f5154cbb8e95536c462412ab\\setup.py'"'"'; __file__='"'"'C:\\Users\\suraj\\AppData\\Local\\Temp\\pip-install-kfis6pkg\\pyaudio_e840b595f5154cbb8e95536c462412ab\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\suraj\AppData\Local\Temp\pip-record-l1f6o9sf\install-record.txt' --single-version-externally-managed --compile
--install-headers 'c:\users\suraj\downloads\romantic-alexa-main\venv\include\site\python3.8\PyAudio' Check the logs for full command output.


what is these error PyAudio is not installing

**Comment by 42sol-eu** [comment]
The error says

```
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
```

pyaudio needs to compile (buildk some code to run. If you have no compiler in your path that fails.

**Comment by 42sol-eu** [comment]
@ashraf-minhaj 
No reply from creator... close this?

**Comment by joelprince2601** [comment]
i dont know what kind of error this is because i have followed all the steps from the vid and checked the code too and i still dont know why this is coming......
![error](https://user-images.githubusercontent.com/63162849/103558775-25910f00-4edb-11eb-9700-d3816d4a6276.PNG)

**Comment by DansDesigns** [comment]
> 
> 
> i dont know what kind of error this is because i have followed all the steps from the vid and checked the code too and i still dont know why this is coming......
> ![error](https://user-images.githubusercontent.com/63162849/103558775-25910f00-4edb-11eb-9700-d3816d4a6276.PNG)

it seems you dont have pywhatkit installed...
