### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by ghost** [ProgrammingHero1/romantic-alexa#35]
Traceback (most recent call last):
  File "C:/Users/usre/PycharmProjects/pythonProject1/main.py", line 59, in <module>
    run_alexa()
  File "C:/Users/usre/PycharmProjects/pythonProject1/main.py", line 36, in run_alexa
    if 'play' in command:
NameError: name 'command' is not defined
None

**Comment by ashraf-minhaj** [comment]
Please see the discussions in issue #5
