### ISSUE TITLE
Please Help It was all working fine and now it isn't working

### ISSUE THREAD

**Issue by khilesh-kumar** [ProgrammingHero1/romantic-alexa#36]
**Please Help It was working and I made my own and that was also working then it showed error**
PS C:\Users\user> & C:/Users/user/AppData/Local/Programs/Python/Python39/python.exe c:/Users/user/g.py
Traceback (most recent call last):
  File "c:\Users\user\g.py", line 60, in <module>
    run_alexa()
  File "c:\Users\user\g.py", line 35, in run_alexa
    command = take_command()
  File "c:\Users\user\g.py", line 31, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

**Comment by Jinoy-Varghese** [comment]
same issue found
`C:\Users\jinoy>python c:/Users/jinoy/Desktop/alexa.py
Traceback (most recent call last):
  File "c:/Users/jinoy/Desktop/alexa.py", line 60, in <module>
    run_alexa()
  File "c:/Users/jinoy/Desktop/alexa.py", line 35, in run_alexa
    command = take_command()
  File "c:/Users/jinoy/Desktop/alexa.py", line 31, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment`

**Comment by khilesh-kumar** [comment]
It's all about microphone.
Just check your microphone is plugged properly or not.
When check my was loosely connected so I connected it. Then I not faced this problem.
Try this solution.

**Comment by Jinoy-Varghese** [comment]
> It's all about microphone.
> Just check your microphone is plugged properly or not.
> When check my was loosely connected so I connected it. Then I not faced this problem.
> Try this solution.

I have a built in microphone in my laptop which is working properly

**Comment by khilesh-kumar** [comment]
So just recheck your command

**Comment by Jinoy-Varghese** [comment]
commands I used are : 
pip install speechRecognition
pip install pyttsx3
pip install pywhatkit
pip install wikipedia
pip install pyjokes

**Comment by Rahulshah192006** [comment]
@Jinoy-Varghese  
install pyaudio
to solve your problem
