### ISSUE TITLE
I had an error installing the " PyAudio" and "portAudio ". I use zorinOs, venv and my python version is the 3.6

### ISSUE THREAD

**Issue by Edgar3g** [ProgrammingHero1/romantic-alexa#43]
Error of the **portAudio**

Traceback (most recent call last):
  File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/portaudio/

##Error of the **PyAudio**

 Using cached https://files.pythonhosted.org/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz
Building wheels for collected packages: PyAudio
  Running setup.py bdist_wheel for PyAudio ... error
  Complete output from command /media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-giuvzwfs/PyAudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp00v680pipip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for PyAudio
  Running setup.py clean for PyAudio
Failed to build PyAudio
Installing collected packages: PyAudio
  Running setup.py install for PyAudio ... error
    Complete output from command /media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-giuvzwfs/PyAudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xewmto71-record/install-record.txt --single-version-externally-managed --compile --install-headers /media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/include/site/python3.6/PyAudio:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    copying src/pyaudio.py -> build/lib.linux-x86_64-3.6
    running build_ext
    building '_portaudio' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/include -I/usr/include/python3.6m -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.6/src/_portaudiomodule.o
    src/_portaudiomodule.c:28:10: fatal error: Python.h: Ficheiro ou directoria inexistente
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-giuvzwfs/PyAudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xewmto71-record/install-record.txt --single-version-externally-managed --compile --install-headers /media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/include/site/python3.6/PyAudio" failed with error code 1 in /tmp/pip-build-giuvzwfs/PyAudio/

**Comment by swapniljadhav98** [comment]
Hey  folks,
I was facing an below error for which i got a resolution:-
Failed building wheel for PyAudio
.
.
..
.
.
Traceback (most recent call last):
  File "e:\romantic-alexa-main\romantic-alexa-main\main.py", line 61, in <module>
    run_alexa()
  File "e:\romantic-alexa-main\romantic-alexa-main\main.py", line 36, in run_alexa
    command = take_command()
  File "e:\romantic-alexa-main\romantic-alexa-main\main.py", line 32, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment
-----------------------------------------------------------
when you get this error there might be 2 chances either your PyAudio package is not imported properly or Alexa is not receiving a proper command

for the first scenario:-
**if tried installing pyaudio using pip install but it's keep on failing the you might need to do it externally i.e you have to download wheel file from python binaries link and the install it.(reference:-https://stackoverflow.com/questions/52283840/i-cant-install-pyaudio-on-windows-how-to-solve-error-microsoft-visual-c-14)**

for the second scenario:-
you have to check what statement is passed in run_alexa() function. i.e you should exactly say the below statement to play the song:- ' Alexa play <song name> ' then on it will recognize the pattern 

> Error of the **portAudio**
> 
> Traceback (most recent call last):
> File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
> status = self.run(options, args)
> File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/commands/install.py", line 353, in run
> wb.build(autobuilding=True)
> File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
> self.requirement_set.prepare_files(self.finder)
> File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
> ignore_dependencies=self.ignore_dependencies))
> File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/req/req_set.py", line 554, in _prepare_file
> require_hashes
> File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
> self.link = finder.find_requirement(self, upgrade)
> File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/index.py", line 465, in find_requirement
> all_candidates = self.find_all_candidates(req.name)
> File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/index.py", line 423, in find_all_candidates
> for page in self._get_pages(url_locations, project_name):
> File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/index.py", line 568, in _get_pages
> page = self._get_page(location)
> File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/index.py", line 683, in _get_page
> return HTMLPage.get_page(link, session=self.session)
> File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/lib/python3.6/site-packages/pip/index.py", line 795, in get_page
> resp.raise_for_status()
> File "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
> raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/portaudio/
> 
> ##Error of the **PyAudio**
> 
> Using cached https://files.pythonhosted.org/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz
> Building wheels for collected packages: PyAudio
> Running setup.py bdist_wheel for PyAudio ... error
> Complete output from command /media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/bin/python3 -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-giuvzwfs/PyAudio/setup.py';f=getattr(tokenize, 'open', open)(**file**);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, **file**, 'exec'))" bdist_wheel -d /tmp/tmp00v680pipip-wheel- --python-tag cp36:
> usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
> or: -c --help [cmd1 cmd2 ...]
> or: -c --help-commands
> or: -c cmd --help
> 
> error: invalid command 'bdist_wheel'
> 
> Failed building wheel for PyAudio
> Running setup.py clean for PyAudio
> Failed to build PyAudio
> Installing collected packages: PyAudio
> Running setup.py install for PyAudio ... error
> Complete output from command /media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/bin/python3 -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-giuvzwfs/PyAudio/setup.py';f=getattr(tokenize, 'open', open)(**file**);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, **file**, 'exec'))" install --record /tmp/pip-xewmto71-record/install-record.txt --single-version-externally-managed --compile --install-headers /media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/include/site/python3.6/PyAudio:
> running install
> running build
> running build_py
> creating build
> creating build/lib.linux-x86_64-3.6
> copying src/pyaudio.py -> build/lib.linux-x86_64-3.6
> running build_ext
> building '_portaudio' extension
> creating build/temp.linux-x86_64-3.6
> creating build/temp.linux-x86_64-3.6/src
> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/include -I/usr/include/python3.6m -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.6/src/_portaudiomodule.o
> src/_portaudiomodule.c:28:10: fatal error: Python.h: Ficheiro ou directoria inexistente
> #include "Python.h"
> ^~~~~~~~~~
> compilation terminated.
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> 
> ```
> ----------------------------------------
> ```
> 
> Command "/media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/bin/python3 -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-giuvzwfs/PyAudio/setup.py';f=getattr(tokenize, 'open', open)(**file**);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, **file**, 'exec'))" install --record /tmp/pip-xewmto71-record/install-record.txt --single-version-externally-managed --compile --install-headers /media/dikenge/460C8FA50C8F8E9D/Aplications_exercice/Isabel_IA/.venv/include/site/python3.6/PyAudio" failed with error code 1 in /tmp/pip-build-giuvzwfs/PyAudio/

**Comment by Thrianadh** [comment]
Try the below method

`pip   install pipwin`
`pipwin install pyaudio`

[Got the solution from this link](https://stackoverflow.com/questions/53866104/pyaudio-failed-to-install-windows-10)

**Comment by Rahulshah192006** [comment]
hi @Edgar3g 
i have the solution 
1: [click here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyaudio)
install as per your python version
then open cmd or powershell 
write `pip install PyAudio
and then press tab for auto complete
