### ISSUE TITLE
This error are encountered

### ISSUE THREAD

**Issue by AwesomeApplicationSolution** [ProgrammingHero1/romantic-alexa#44]
"C:\Users\Krishna Purohit\PycharmProjects\Snaya\venv\Scripts\python.exe" "C:/Users/Krishna Purohit/PycharmProjects/Snaya/main.py"
Traceback (most recent call last):
  File "C:/Users/Krishna Purohit/PycharmProjects/Snaya/main.py", line 62, in <module>
    run_alexa()
  File "C:/Users/Krishna Purohit/PycharmProjects/Snaya/main.py", line 37, in run_alexa
    command = take_command()
  File "C:/Users/Krishna Purohit/PycharmProjects/Snaya/main.py", line 32, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

Process finished with exit code 1

**Comment by irenetsk** [comment]
Same error as mine. 
Also, I had trouble installing both pyAudio and portAudio.

**Comment by Amit-Chaurasiya** [comment]
I also got the same error, does someone have any solution?
