### ISSUE TITLE
Some Issue if any one could help!!!

### ISSUE THREAD

**Issue by Sanchit0323** [ProgrammingHero1/romantic-alexa#53]
Traceback (most recent call last):
  File "C:/Users/KIIT/PycharmProjects/alexa/main.py", line 60, in <module>
    run_alexa()
  File "C:/Users/KIIT/PycharmProjects/alexa/main.py", line 35, in run_alexa
    command = take_command()
  File "C:/Users/KIIT/PycharmProjects/alexa/main.py", line 31, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

**Comment by Prince2347X** [comment]
Duplicate of #57

**Comment by Prince2347X** [comment]
#57

**Comment by Sanchit0323** [comment]
C:\Users\KIIT\PycharmProjects\alexa\venv\Scripts\python.exe C:/Users/KIIT/PycharmProjects/alexa/main.py
No command detected! Alexa has stopped working 

Process finished with exit code 0
Stops instantly.... :(

**Comment by Prince2347X** [comment]
> C:\Users\KIIT\PycharmProjects\alexa\venv\Scripts\python.exe C:/Users/KIIT/PycharmProjects/alexa/main.py
> No command detected! Alexa has stopped working 
> 
> Process finished with exit code 0
> Stops instantly.... :(

It is because you didn't give any command!🙄Or maybe your mic has a problem...

**Comment by Sanchit0323** [comment]
import speech_recognition as sr
import pyttsx3
import pywhatkit
import datetime
import wikipedia
import pyjokes

listener = sr.Recognizer()
engine = pyttsx3.init()
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[1].id)


def talk(text):
    engine.say(text)
    engine.runAndWait()


def take_command():
    try:
        with sr.Microphone() as source:
            print('listening...')
            voice = listener.listen(source)
            command = listener.recognize_google(voice)
            command = command.lower()
            if 'alexa' in command:
                command = command.replace('alexa', '')
                print(command)
    except:
        pass
    return command


def run_alexa():
    command = take_command()
    print(command)
    if 'play' in command:
        song = command.replace('play', '')
        talk('playing ' + song)
        pywhatkit.playonyt(song)
    elif 'time' in command:
        time = datetime.datetime.now().strftime('%I:%M %p')
        talk('Current time is ' + time)
    elif 'who the heck is' in command:
        person = command.replace('who the heck is', '')
        info = wikipedia.summary(person, 1)
        print(info)
        talk(info)
    elif 'date' in command:
        talk('sorry, I have a headache')
    elif 'are you single' in command:
        talk('I am in a relationship with wifi')
    elif 'joke' in command:
        talk(pyjokes.get_joke())
    else:
        talk('Please say the command again.')


while True:
    try:
        run_alexa()
    except UnboundLocalError:
        print("No command detected! Alexa has stopped working ")
        break

**Comment by Sanchit0323** [comment]
> > C:\Users\KIIT\PycharmProjects\alexa\venv\Scripts\python.exe C:/Users/KIIT/PycharmProjects/alexa/main.py
> > No command detected! Alexa has stopped working
> > Process finished with exit code 0
> > Stops instantly.... :(
> 
> It is because you didn't give any command!🙄Or maybe your mic has a problem...

import speech_recognition as sr
import pyttsx3
import pywhatkit
import datetime
import wikipedia
import pyjokes

listener = sr.Recognizer()
engine = pyttsx3.init()
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[1].id)


def talk(text):
    engine.say(text)
    engine.runAndWait()


def take_command():
    try:
        with sr.Microphone() as source:
            print('listening...')
            voice = listener.listen(source)
            command = listener.recognize_google(voice)
            command = command.lower()
            if 'alexa' in command:
                command = command.replace('alexa', '')
                print(command)
    except:
        pass
    return command


def run_alexa():
    command = take_command()
    print(command)
    if 'play' in command:
        song = command.replace('play', '')
        talk('playing ' + song)
        pywhatkit.playonyt(song)
    elif 'time' in command:
        time = datetime.datetime.now().strftime('%I:%M %p')
        talk('Current time is ' + time)
    elif 'who the heck is' in command:
        person = command.replace('who the heck is', '')
        info = wikipedia.summary(person, 1)
        print(info)
        talk(info)
    elif 'date' in command:
        talk('sorry, I have a headache')
    elif 'are you single' in command:
        talk('I am in a relationship with wifi')
    elif 'joke' in command:
        talk(pyjokes.get_joke())
    else:
        talk('Please say the command again.')


while True:
    try:
        run_alexa()
    except UnboundLocalError:
        print("No command detected! Alexa has stopped working ")
        break

**Comment by jayasri1616** [comment]
same thing is happened with my code
