### ISSUE TITLE
I can't run the code 

### ISSUE THREAD

**Issue by ghost** [ProgrammingHero1/romantic-alexa#55]
I havea problem and I installed all the packages completely
this is problem that shows after running the code 
Traceback (most recent call last):
File "D:/Coding/Fun With Python/PyCharm/PyCharm Projects/Virtual Assistant/main.py", line 70, in
run_python()
File "D:/Coding/Fun With Python/PyCharm/PyCharm Projects/Virtual Assistant/main.py", line 35, in run_python
command = take_command()
File "D:/Coding/Fun With Python/PyCharm/PyCharm Projects/Virtual Assistant/main.py", line 31, in take_command
return command
UnboundLocalError: local variable 'command' referenced before `assignment```

**Comment by Prince2347X** [comment]
As much as i know, the error is telling that you've used the command variable before assigning it's value. So a quick fix would be make the ### **command** variable at the starting of the code (of in the function)

**Comment by eranga-mohotty** [comment]
`pip install pyaudio`
solved this problem for me.
