### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by BenEgeTR** [ProgrammingHero1/romantic-alexa#57]
listening...
Traceback (most recent call last):
  File "c:\Users\Egehan\Desktop\alexa\E.py", line 58, in <module>
    run_alexa()
  File "c:\Users\Egehan\Desktop\alexa\E.py", line 34, in run_alexa
    command = take_command()
  File "c:\Users\Egehan\Desktop\alexa\E.py", line 30, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

**Comment by Prince2347X** [comment]
When you're calling the function at the end, use a try-except block to handle the exceptions. See this ↙
```py
while True:
    try:
        run_alexa()
    except UnboundLocalError:
        print("No command detected! Alexa has stopped working ")
        break
```
Hope this'll work!

**Comment by aarjitpaudel** [comment]
> listening...
> Traceback (most recent call last):
> File "c:\Users\Egehan\Desktop\alexa\E.py", line 58, in
> run_alexa()
> File "c:\Users\Egehan\Desktop\alexa\E.py", line 34, in run_alexa
> command = take_command()
> File "c:\Users\Egehan\Desktop\alexa\E.py", line 30, in take_command
> return command
> UnboundLocalError: local variable 'command' referenced before assignment

while True:
    try:
        run_alexa()
    except UnboundLocalError:
        pass

**Comment by eranga-mohotty** [comment]
`pip install pyaudio`
solved this problem for me. speech_recognition was throwing an error without it

**Comment by vampirepapi** [comment]
Try this (in admin mode command prompt):
```
pip install pipwin
pipwin install pyaudio
```

**Comment by adityayadaviit** [comment]
> When you're calling the function at the end, use a try-except block to handle the exceptions. See this ↙
> 
> ```python
> while True:
>     try:
>         run_alexa()
>     except UnboundLocalError:
>         print("No command detected! Alexa has stopped working ")
>         break
> ```
> 
> Hope this'll work!

not working
new error :
IndentationError: expected an indented block

**Comment by Prince2347X** [comment]
> not working
> new error :
> IndentationError: expected an indented block

Check the indentation of your code properly!..🤷‍♂️

**Comment by adityayadaviit** [comment]
while running code it gives

[Running] python -u "c:\Users\91721\Desktop\jarvis\main.py"

[Done] exited with code=0 in 1.462 seconds

**Comment by Jinoy-Varghese** [comment]
> Try this (in admin mode command prompt):
> 
> ```
> pip install pipwin
> pipwin install pyaudio
> ```

Thanks bro it is working properly now

**Comment by mastermindharsh** [comment]
> Try this (in admin mode command prompt):
> 
> ```
> pip install pipwin
> pipwin install pyaudio
> ```

worked for me

**Comment by jmherrera11** [comment]
I did this and just it extends a little more before error

while True:
    try:
        run_alexa()
    except UnboundLocalError:
        print("No command detected! Alexa has stopped working ")
        run_alexa()

I think is needed to handle the UnboundLocalError: local variable 'command' referenced before assignment

**Comment by jmherrera11** [comment]
This a Lousy solution but at least it will continue listening:

while True:
    try:
        run_alexa()
    except UnboundLocalError:
        print("No command detected! Alexa has stopped working ")
        command = "."
