### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by adityayadaviit** [ProgrammingHero1/romantic-alexa#64]
UnboundLocalError: local variable 'command' referenced before assignment

while running it gives error

**Comment by ColinSather** [comment]
Are you positive you have pyaudio installed? If not run the command `pip install PyAudio`.

**Comment by adityayadaviit** [comment]
i installed pyaudio

**Comment by adityayadaviit** [comment]
while installing pyaudio it gives a erro

ERROR: Command errored out with exit status 1:
     command:
'c:\users\91721\appdata\local\programs\python\python39\python.exe' -u -c
'import
sys, setuptools, tokenize; sys.argv[0] =
'"'"'C:\\Users\\91721\\AppData\\Local\\Temp\\pip-install-sieup9gj\\pyaudio\\setup.py'"'"';
__file__='"'"'C:\\Users\\91721\\AppData\\Local\\Temp\\pip-install-sieup9gj\\pyaudio\\setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record
'C:\Users\91721\AppData\Local\Temp\pip-record-_xezuzk3\install-record.txt'
--single-version-externally-managed --compile --install-headers
'c:\users\91721\appdata\local\programs\python\python39\Include\pyaudio'
         cwd:
C:\Users\91721\AppData\Local\Temp\pip-install-sieup9gj\pyaudio\
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    copying src\pyaudio.py -> build\lib.win-amd64-3.9
    running build_ext
    building '_portaudio' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools
for Visual Studio":
https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1:
'c:\users\91721\appdata\local\programs\python\python39\python.exe' -u -c
'import sys, setuptools, tokenize; sys.argv[0] =
'"'"'C:\\Users\\91721\\AppData\\Local\\Temp\\pip-install-sieup9gj\\pyaudio\\setup.py'"'"';
__file__='"'"'C:\\Users\\91721\\AppData\\Local\\Temp\\pip-install-sieup9gj\\pyaudio\\setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record
'C:\Users\91721\AppData\Local\Temp\pip-record-_xezuzk3\install-record.txt'
--single-version-externally-managed --compile --install-headers
'c:\users\91721\appdata\local\programs\python\python39\Include\pyaudio'
Check the logs for full command output.

**Comment by Prince2347X** [comment]
@adityayadaviit Install pyaudio by running these commands:
```text
pip install pipwin
pipwin install pyaudio
```
And let me know still if you're getting any error(s).

**Comment by adityayadaviit** [comment]
it worked but while running the code it tells listening... but when I tell
what is the time or alexa what is the time it still gives listening...

**Comment by Yewin100** [comment]
I TRIED THIS BUT IT IS NOT STILL WORKING

**Comment by Yewin100** [comment]
pipwin install pyaudio
Package `pyaudio` found in cache
Downloading package . . .
https://download.lfd.uci.edu/pythonlibs/q4trcu4l/PyAudio-0.2.11-cp39-cp39-win_amd64.whl
PyAudio-0.2.11-cp39-cp39-win_amd64.whl
Traceback (most recent call last):
  File "C:\Users\Pct\PycharmProjects\Yewin\venv\Scripts\pipwin-script.py", line 33, in <module>
    sys.exit(load_entry_point('pipwin==0.5.1', 'console_scripts', 'pipwin')())
  File "c:\users\pct\pycharmprojects\yewin\venv\lib\site-packages\pipwin\command.py", line 103, in main
    cache.install(package)
  File "c:\users\pct\pycharmprojects\yewin\venv\lib\site-packages\pipwin\pipwin.py", line 300, in install
    wheel_file = self.download(requirement)
  File "c:\users\pct\pycharmprojects\yewin\venv\lib\site-packages\pipwin\pipwin.py", line 294, in download
    return self._download(requirement, dest)
  File "c:\users\pct\pycharmprojects\yewin\venv\lib\site-packages\pipwin\pipwin.py", line 290, in _download
    obj.start()
  File "c:\users\pct\pycharmprojects\yewin\venv\lib\site-packages\pySmartDL\pySmartDL.py", line 267, in start
    urlObj = urllib.request.urlopen(req, timeout=self.timeout, context=self.context)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
