### ISSUE TITLE
Problem with 'command' variable. UnboundLocalError

### ISSUE THREAD

**Issue by Amit-Chaurasiya** [ProgrammingHero1/romantic-alexa#66]
Can someone help me with this?

Traceback (most recent call last):
  File "C:/Users/Amit Chaurasiya/PycharmProjects/AI Assistant/main.py", line 60, in <module>
    run_alexa()
  File "C:/Users/Amit Chaurasiya/PycharmProjects/AI Assistant/main.py", line 35, in run_alexa
    command = take_command()
  File "C:/Users/Amit Chaurasiya/PycharmProjects/AI Assistant/main.py", line 31, in take_command
    return command
**UnboundLocalError: local variable 'command' referenced before assignment**

**Comment by rohithaditya** [comment]
yep arriving for me too

**Comment by yusufekivilcim** [comment]
Same problem with me too

**Comment by aamirhussain350** [comment]
The issue simply says your returning variable 'command' before assignment or you have not defined the variable 'command' and referenced it.
Please provide your source code so anyone can help further. Thanks!

**Comment by Prince2347X** [comment]
@aamirhussain350 @rohithaditya @Amit-Chaurasiya 

Just a little change in line 23:
```py
voice = listener.listen(source, None, 10)
```
`10` is the time in seconds for the source before it's timeout. You can increase it too.
(If the above one doesn't work, try this ↓)
When you're calling the function at the end, use a try-except block to handle the exceptions. See this ↙
```py
while True:
    try:
        run_alexa()
    except UnboundLocalError:
        print("No command detected! Alexa has stopped working ")
        break
```
Hope this'll work!

**Comment by xaadix13** [comment]
Sir, its just simply saying 
No command detected! Alexa has stopped working 
Without taking any input. Can you please helpme in that

**Comment by senthil-pandi** [comment]
> Sir, its just simply saying
> No command detected! Alexa has stopped working
> Without taking any input. Can you please helpme in that

Did you found the solution
