### ISSUE TITLE
sir i am getting below error and alexa is not listening and directly saying process finished with code0.Sir please help me to remove this error

### ISSUE THREAD

**Issue by Hemanth4978** [ProgrammingHero1/romantic-alexa#69]
C:\Users\LENOVO\PycharmProjects\Angelsara\venv\Scripts\python.exe C:/Users/LENOVO/PycharmProjects/Angelsara/main.py
Traceback (most recent call last):
  File "C:\Users\LENOVO\PycharmProjects\Angelsara\main.py", line 60, in <module>
    run_alexa()
  File "C:\Users\LENOVO\PycharmProjects\Angelsara\main.py", line 35, in run_alexa
    command = take_command()
  File "C:\Users\LENOVO\PycharmProjects\Angelsara\main.py", line 31, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

Process finished with exit code 0

**Comment by Prince2347X** [comment]
Duplicate of #66
Kindly check the solution [there 🙂](https://github.com/ProgrammingHero1/romantic-alexa/issues/66#issuecomment-839818566)
