### ISSUE TITLE
not running

### ISSUE THREAD

**Issue by Magrosunrg** [ProgrammingHero1/romantic-alexa#85]
Traceback (most recent call last):
  File "C:\Users\magro\PycharmProjects\alexa\venv\lib\site-packages\pywhatkit\main.py", line 310, in <module>
    requests.get("https://www.google.com")
  File "C:\Users\magro\PycharmProjects\alexa\venv\lib\site-packages\requests\api.py", line 55, in get
    return request('get', url, **kwargs)
  File "C:\Users\magro\PycharmProjects\alexa\venv\lib\site-packages\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\magro\PycharmProjects\alexa\venv\lib\site-packages\requests\sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\magro\PycharmProjects\alexa\venv\lib\site-packages\requests\sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\magro\PycharmProjects\alexa\venv\lib\site-packages\requests\adapters.py", line 282, in send
    resp = conn.urlopen(
  File "C:\Users\magro\PycharmProjects\alexa\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 423, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "C:\Users\magro\PycharmProjects\alexa\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 238, in _get_conn
    return conn or self._new_conn()
  File "C:\Users\magro\PycharmProjects\alexa\venv\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 560, in _new_conn
    connection = VerifiedHTTPSConnection(host=self.host,
TypeError: __init__() got an unexpected keyword argument 'strict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\magro\PycharmProjects\alexa\main.py", line 3, in <module>
    import pywhatkit
  File "C:\Users\magro\PycharmProjects\alexa\venv\lib\site-packages\pywhatkit\__init__.py", line 8, in <module>
    from pywhatkit.main import print_sleep_time, check_window, sendwhatmsg, sendwhatmsg_to_group, info, playonyt, search, close_tab, sendwhatmsg_instantly, sendwhats_image
  File "C:\Users\magro\PycharmProjects\alexa\venv\lib\site-packages\pywhatkit\main.py", line 314, in <module>
    raise InternetException(
pywhatkit.exceptions.InternetException: NO INTERNET - Pywhatkit needs active internet connection

Process finished with exit code 1

**Comment by Prince2347X** [comment]
Read the last line of the error "Pywhatkit needs active internet connection"
