### ISSUE TITLE
showing error in 3 lines 

### ISSUE THREAD

**Issue by bhaskarkumar1** [ProgrammingHero1/romantic-alexa#87]
Traceback (most recent call last):
  File "C:\Users\bhask\PycharmProjects\Alexa\main.py", line 60, in <module>
    run_alexa()
  File "C:\Users\bhask\PycharmProjects\Alexa\main.py", line 35, in run_alexa
    command = take_command()
  File "C:\Users\bhask\PycharmProjects\Alexa\main.py", line 31, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment
![alex](https://user-images.githubusercontent.com/84345649/131242756-969636a7-f90d-419a-bf55-4643aeb9b9af.png)

**Comment by Mrinank-Bhowmick** [comment]
> Traceback (most recent call last):
> File "C:\Users\bhask\PycharmProjects\Alexa\main.py", line 60, in
> run_alexa()
> File "C:\Users\bhask\PycharmProjects\Alexa\main.py", line 35, in run_alexa
> command = take_command()
> File "C:\Users\bhask\PycharmProjects\Alexa\main.py", line 31, in take_command
> return command
> UnboundLocalError: local variable 'command' referenced before assignment
> ![alex](https://user-images.githubusercontent.com/84345649/131242756-969636a7-f90d-419a-bf55-4643aeb9b9af.png)

Generally this error occurs when the pyaudio module is not installed properly ,sounds wierd but you can try
pip install pipwin
pipwin install pyaudio
In terminal.
Hope that helps

**Comment by soham2710** [comment]
![image](https://user-images.githubusercontent.com/42056502/135407182-949e107a-fa94-4a51-a068-76e1b431d43d.png)


Pyaudio didnt work and also The initial error was with the pywhatkit, though pip installing pywhatkit was success.

![image](https://user-images.githubusercontent.com/42056502/135407337-8ee42ea4-f08a-4b18-ac6a-cbe3db7a40f2.png)


Kindly suggest for the next step. I am trying this on Google Colab.

**Comment by Smitthyy** [comment]
I have this same issue, I have gone through many ways of installing pyaudio and it's made no difference. If anyone else has any further tips I'd love to know.

**Comment by jmherrera11** [comment]
> I have this same issue, I have gone through many ways of installing pyaudio and it's made no difference. If anyone else has any further tips I'd love to know.

It worked for me. Thanks a lot

**Comment by jmherrera11** [comment]
"Generally this error occurs when the pyaudio module is not installed properly ,sounds wierd but you can try
pip install pipwin
pipwin install pyaudio
In terminal.
Hope that helps"  ---->>>> IT WORKED X ME. Thanks EFFLUX110

**Comment by Monika6053** [comment]
![Screenshot (365)](https://user-images.githubusercontent.com/91683098/177039972-bf2d2352-7afc-4ea1-869a-ba3a43ae98b9.png)
same problem
Anybody please help me?

**Comment by jinimbi** [comment]
I installed the pyaudio but I am still facing the same problem.
