### ISSUE TITLE
UnboundLocalError: local variable 'command' referenced before assignment

### ISSUE THREAD

**Issue by prasadbhosale80** [ProgrammingHero1/romantic-alexa#9]
I am using this code in rasberry pi and it shows following error

Traceback (most recent call last):
  File "/home/pi/Project/alexa.py", line 60, in <module>
    run_alexa()
  File "/home/pi/Project/alexa.py", line 35, in run_alexa
    command = take_command()
  File "/home/pi/Project/alexa.py", line 31, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

**Comment by ashraf-minhaj** [comment]
See this issue - https://github.com/ProgrammingHero1/romantic-alexa/issues/5
