### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by urmil042y** [ProgrammingHero1/romantic-alexa#94]
File "c:\Users\Asus\Desktop\alexa\alexa.py", line 59, in <module>
    run_alexa()
  File "c:\Users\Asus\Desktop\alexa\alexa.py", line 35, in run_alexa
    command = take_command()
  File "c:\Users\Asus\Desktop\alexa\alexa.py", line 31, in take_command
    return command
UnboundLocalError: local variable 'command' referenced before assignment

**Comment by jmherrera11** [comment]
> File "c:\Users\Asus\Desktop\alexa\alexa.py", line 59, in run_alexa() File "c:\Users\Asus\Desktop\alexa\alexa.py", line 35, in run_alexa command = take_command() File "c:\Users\Asus\Desktop\alexa\alexa.py", line 31, in take_command return command UnboundLocalError: local variable 'command' referenced before assignment

samething

**Comment by Goushiksam** [comment]
solution kudraaaaaaaaaa juniiiiiii

**Comment by yenupuri** [comment]
C:\Users\ygyan\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/ygyan/PycharmProjects/pythonProject/main.py
Traceback (most recent call last):
  File "C:\Users\ygyan\PycharmProjects\pythonProject\main.py", line 3, in <module>
    import pywhatkit
  File "C:\Users\ygyan\PycharmProjects\pythonProject\venv\lib\site-packages\pywhatkit\__init__.py", line 4, in <module>
    from pywhatkit.mainfunctions import watch_tutorial_in_English, watch_tutorial_in_Hindi, developer_contact, showHistory, shutdown, cancelShutdown, prnt_sleeptm, check_window, sendwhatmsg, info, playonyt, image_to_ascii_art, search, help 
  File "C:\Users\ygyan\PycharmProjects\pythonProject\venv\lib\site-packages\pywhatkit\mainfunctions.py", line 3, in <module>
    import pyautogui as pg
  File "C:\Users\ygyan\PycharmProjects\pythonProject\venv\lib\site-packages\pyautogui\__init__.py", line 221, in <module>
    locateOnWindow.__doc__ = pyscreeze.locateOnWindow.__doc__
AttributeError: module 'pyscreeze' has no attribute 'locateOnWindow'

Process finished with exit code 1
 solution for this
