### ISSUE TITLE
pywhatkit not found

### ISSUE THREAD

**Issue by mIScHEIF4** [ProgrammingHero1/romantic-alexa#95]
I am getting this issue even when I installed the pywhatkit module......Pls, help me.

"C:\Users\acer pc\anaconda3\python.exe" "C:/Users/acer pc/PycharmProjects/Maria/main.py"
Traceback (most recent call last):
  File "C:/Users/acer pc/PycharmProjects/Maria/main.py", line 3, in <module>
    import pywhatkit
ModuleNotFoundError: No module named 'pywhatkit'

Process finished with exit code 1

**Comment by Aryan-Aggarwal** [comment]
open the terminal of your project and write
pip install pywhatkit
the installation will be completed then restart your ide 
your problem will be solved

**Comment by mIScHEIF4** [comment]
It's still showing the same.

**Comment by mIScHEIF4** [comment]
ERROR: Could not find a version that satisfies the requirement pywatkit (from versions: none)
ERROR: No matching distribution found for pywatkit



The next Error...

**Comment by N0THSA** [comment]
you misspelled it

**Comment by yenupuri** [comment]
C:\Users\ygyan\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/ygyan/PycharmProjects/pythonProject/main.py
Traceback (most recent call last):
  File "C:\Users\ygyan\PycharmProjects\pythonProject\main.py", line 3, in <module>
    import pywhatkit
  File "C:\Users\ygyan\PycharmProjects\pythonProject\venv\lib\site-packages\pywhatkit\__init__.py", line 4, in <module>
    from pywhatkit.mainfunctions import watch_tutorial_in_English, watch_tutorial_in_Hindi, developer_contact, showHistory, shutdown, cancelShutdown, prnt_sleeptm, check_window, sendwhatmsg, info, playonyt, image_to_ascii_art, search, help 
  File "C:\Users\ygyan\PycharmProjects\pythonProject\venv\lib\site-packages\pywhatkit\mainfunctions.py", line 3, in <module>
    import pyautogui as pg
  File "C:\Users\ygyan\PycharmProjects\pythonProject\venv\lib\site-packages\pyautogui\__init__.py", line 221, in <module>
    locateOnWindow.__doc__ = pyscreeze.locateOnWindow.__doc__
AttributeError: module 'pyscreeze' has no attribute 'locateOnWindow'

Process finished with exit code 1

any solution for this
